databases:
- name: your-postgresql-database
  user: your_db_user
  plan: free # Or your plan
  databaseName: your_db_name

services:
- type: web
  name: your-flask-app
  runtime: python3.9, python3.10, python3.13 # Or your Python version
  plan: free # Or your Render plan
  region: your-render-region
  branch: main # Or your branch
  startCommand: gunicorn --worker-class gevent --timeout 600 --bind 0.0.0.0:$PORT main:app
  buildCommand: pip install -r requirements.txt
  envVars:
  - key: DB_HOST
    fromDatabase:
      name: your-postgresql-database
      property: host
  - key: DB_NAME
    fromDatabase:
      name: your-postgresql-database
      property: databaseName
  - key: DB_USER
    fromDatabase:
      name: your-postgresql-database
      property: user
  - key: DB_PASSWORD
    fromDatabase:
      name: your-postgresql-database
      property: password
      sync: false # Hide value
  - key: PROJECT_ID
    value: your-vertex-ai-project-id
  - key: LOCATION
    value: your-vertex-ai-location
  - key: Gemini_API
    sync: false # Hide value
  # Add other API keys or sensitive information here, using sync: false

  healthCheckPath: /health # Add a health check route in your Flask app

- type: static
  name: your-static-site
  repo: https://github.com/your-username/your-repo # Or your repo URL
  branch: main # Or your branch
  region: US
  plan: free # Or your plan
  # Add build or other commands if needed
